# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 667186f0da7dc189e6921a7441b783fb7ffdc1be2d2d8edf1d63c5c8552e7055137b85819cb062e00a3894f60f07e9df797ea3c43117a138087bf0f6b35a5bc3

test:
  secret_key_base: c6c2d6de0cf351e7faa3ce13fdc500b606712850e71815bda10b0d458af49b3f7b0afa8f545c07e29e947f399cb9ca2ac6306f6ab514038e377dc5bc3fd281f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
